[package]
name = "ctx"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.102"
clap = { version = "4.5.60", features = ["derive"] }
dirs = "6.0.0"
kdl = "6.5.0"
serde = { version = "1.0.228", features = ["derive"] }
tmux_interface = "0.3.2"
